# Generated by Django 6.0.5 on 2026-07-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_quotation_procurementrequest_selected_quotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequest',
            name='payment_proof',
            field=models.FileField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
    ]
