# Generated by Django 6.0.5 on 2026-07-10 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('procurement', '0004_alter_procurementrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequest',
            name='new_item_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='procurementrequest',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
    ]
