# Generated by Django 6.0.5 on 2026-07-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_procurementrequest_new_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
