# Generated by Django 6.0.5

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('procurement', '0006_procurementrequest_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurementrequest',
            name='status',
            field=models.CharField(
                choices=[
                    ('DRAFT', 'Draft'),
                    ('PENDING', 'Pending'),
                    ('WAITING_PAYMENT', 'Waiting for Payment'),
                    ('PAYMENT_RECEIVED', 'Payment Received'),
                    ('REJECTED', 'Rejected'),
                    ('DELIVERED', 'Delivered'),
                ],
                default='DRAFT',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='payment_confirmed_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='payment_confirmations',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='payment_received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
